[2024-01-26 22:22:56,861: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-26 22:22:56,867: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-26 22:22:56,876: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-26 22:22:56,876: INFO: common: created directory at: artifacts]
[2024-01-26 22:22:56,877: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-26 22:22:56,878: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-26 22:36:04,099: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-26 22:36:05,285: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-27 19:27:38,357: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 19:27:38,367: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 19:27:38,369: INFO: common: created directory at: artifacts]
[2024-01-27 19:27:38,371: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-27 19:30:47,736: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 19:30:47,738: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 19:30:47,740: INFO: common: created directory at: artifacts]
[2024-01-27 19:30:47,742: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-27 19:31:38,242: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-27 19:41:40,071: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-27 19:41:40,073: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 19:41:40,076: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 19:41:40,077: INFO: common: created directory at: artifacts]
[2024-01-27 19:41:40,077: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-27 19:41:40,078: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 19:42:29,771: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 19:42:30,324: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-27 19:44:08,865: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-27 19:44:08,867: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 19:44:08,869: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 19:44:08,869: INFO: common: created directory at: artifacts]
[2024-01-27 19:44:08,871: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-27 19:44:08,871: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 19:45:08,879: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 19:45:09,446: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-27 19:45:09,446: INFO: main: *******************]
[2024-01-27 19:45:09,446: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-01-27 19:45:09,448: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 19:45:09,451: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 19:45:09,452: INFO: common: created directory at: artifacts]
[2024-01-27 19:45:09,452: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-27 19:45:09,865: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-27 19:45:10,110: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-01-27 20:18:18,296: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-27 20:18:18,309: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:18:18,316: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:18:18,317: INFO: common: created directory at: artifacts]
[2024-01-27 20:18:18,317: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-27 20:18:18,318: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 20:19:20,786: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 20:19:21,327: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-27 20:19:21,328: INFO: main: *******************]
[2024-01-27 20:19:21,328: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-01-27 20:19:21,331: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:19:21,333: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:19:21,334: INFO: common: created directory at: artifacts]
[2024-01-27 20:19:21,335: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-27 20:19:21,807: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-27 20:19:22,131: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-01-27 20:20:40,829: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:20:40,834: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:20:40,837: INFO: common: created directory at: artifacts]
[2024-01-27 20:20:40,839: INFO: common: created directory at: artifacts\training]
[2024-01-27 20:23:11,828: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:23:11,833: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:23:11,834: INFO: common: created directory at: artifacts]
[2024-01-27 20:23:11,836: INFO: common: created directory at: artifacts\training]
[2024-01-27 20:41:43,007: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-27 20:41:43,010: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:41:43,013: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:41:43,014: INFO: common: created directory at: artifacts]
[2024-01-27 20:41:43,014: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-27 20:41:43,015: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 20:43:20,655: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 20:43:21,291: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-27 20:43:21,292: INFO: main: *******************]
[2024-01-27 20:43:21,292: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-01-27 20:43:21,294: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:43:21,297: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:43:21,297: INFO: common: created directory at: artifacts]
[2024-01-27 20:43:21,298: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-27 20:43:21,745: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-27 20:43:22,206: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-01-27 20:43:22,207: INFO: main: *******************]
[2024-01-27 20:43:22,207: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-27 20:43:22,209: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:43:22,212: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:43:22,213: INFO: common: created directory at: artifacts]
[2024-01-27 20:43:22,214: INFO: common: created directory at: artifacts\training]
[2024-01-27 20:43:22,214: ERROR: main: "'ConfigBox' object has no attribute 'epochs'"]
Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'EPOCHS'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'EPOCHS'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'EPOCHS'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'EPOCHS'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'epochs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'epochs'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'epochs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ML Project\kidney_disease_detection\main.py", line 33, in <module>
    model_trainer.main()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training_config = config.get_training_config()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\config\configuration.py", line 66, in get_training_config
    params_epochs=params.EPOCHS,
  File "box\config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'epochs'"
[2024-01-27 20:45:14,586: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:45:14,594: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:45:14,596: INFO: common: created directory at: artifacts]
[2024-01-27 20:45:14,597: INFO: common: created directory at: artifacts\training]
[2024-01-27 20:46:27,095: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-27 20:46:27,098: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:46:27,100: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:46:27,101: INFO: common: created directory at: artifacts]
[2024-01-27 20:46:27,102: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-27 20:46:27,103: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 20:48:00,945: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 20:48:01,577: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-27 20:48:01,577: INFO: main: *******************]
[2024-01-27 20:48:01,578: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-01-27 20:48:01,580: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:48:01,582: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:48:01,582: INFO: common: created directory at: artifacts]
[2024-01-27 20:48:01,583: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-27 20:48:02,086: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-27 20:48:02,377: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-01-27 20:48:02,378: INFO: main: *******************]
[2024-01-27 20:48:02,378: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-27 20:48:02,381: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:48:02,384: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:48:02,385: INFO: common: created directory at: artifacts]
[2024-01-27 20:48:02,386: INFO: common: created directory at: artifacts\training]
[2024-01-27 20:48:39,543: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-02-08 22:57:57,834: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-08 22:57:57,849: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-08 22:57:57,853: INFO: common: created directory at: artifacts]
[2024-02-08 22:58:17,466: INFO: common: json file saved at: scores.json]
[2024-02-08 22:58:28,258: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-08 22:58:29,842: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmpouszrem3\model\data\model\assets]
[2024-02-08 23:02:00,819: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow-artifacts/artifacts/95841584265043d1baabf1dcf05389f0/41070d4228a0474cbe4853a586caa5fb/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-02-08 23:07:39,422: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-08 23:07:39,430: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-08 23:07:39,432: INFO: common: created directory at: artifacts]
[2024-02-08 23:07:57,806: INFO: common: json file saved at: scores.json]
[2024-02-08 23:08:19,606: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-08 23:08:19,614: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-08 23:08:19,618: INFO: common: created directory at: artifacts]
[2024-02-08 23:08:37,887: INFO: common: json file saved at: scores.json]
[2024-02-08 23:09:14,841: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-08 23:09:14,849: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-08 23:09:14,853: INFO: common: created directory at: artifacts]
[2024-02-08 23:09:33,888: INFO: common: json file saved at: scores.json]
[2024-02-08 23:11:42,937: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-08 23:11:42,953: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-08 23:11:42,957: INFO: common: created directory at: artifacts]
[2024-02-08 23:12:02,071: INFO: common: json file saved at: scores.json]
[2024-02-08 23:12:02,224: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow/runs/create]
[2024-02-08 23:13:23,707: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-08 23:13:23,714: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-08 23:13:23,718: INFO: common: created directory at: artifacts]
[2024-02-08 23:13:42,966: INFO: common: json file saved at: scores.json]
[2024-02-09 00:53:52,873: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 00:53:52,878: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 00:53:52,881: INFO: common: created directory at: artifacts]
[2024-02-09 00:54:11,859: INFO: common: json file saved at: scores.json]
[2024-02-09 11:13:58,245: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 11:13:58,256: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 11:13:58,259: INFO: common: created directory at: artifacts]
[2024-02-09 11:14:17,423: INFO: common: json file saved at: scores.json]
[2024-02-09 11:17:39,154: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 11:17:39,168: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 11:17:39,171: INFO: common: created directory at: artifacts]
[2024-02-09 11:17:57,530: INFO: common: json file saved at: scores.json]
[2024-02-09 11:27:31,575: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 11:27:31,582: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 11:27:31,585: INFO: common: created directory at: artifacts]
[2024-02-09 11:27:49,751: INFO: common: json file saved at: scores.json]
[2024-02-09 11:47:48,687: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 11:47:48,695: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 11:47:48,699: INFO: common: created directory at: artifacts]
[2024-02-09 11:48:07,276: INFO: common: json file saved at: scores.json]
[2024-02-09 20:47:58,913: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 20:47:58,921: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 20:47:58,924: INFO: common: created directory at: artifacts]
[2024-02-09 20:48:19,757: INFO: common: json file saved at: scores.json]
[2024-02-09 21:08:45,800: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 21:08:45,811: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 21:08:45,813: INFO: common: created directory at: artifacts]
[2024-02-09 21:09:01,021: INFO: common: json file saved at: scores.json]
[2024-02-09 21:09:05,770: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-09 21:09:06,583: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmp9ins6pol\model\data\model\assets]
[2024-02-09 21:10:42,423: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow-artifacts/artifacts/e33da3fbd6fd4dbca196d26da02ae894/d779d3e651874f389885ca13a5ea937f/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-02-09 21:13:51,097: WARNING: connectionpool: Retrying (Retry(total=3, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow-artifacts/artifacts/e33da3fbd6fd4dbca196d26da02ae894/d779d3e651874f389885ca13a5ea937f/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-02-09 21:14:30,243: WARNING: connectionpool: Retrying (Retry(total=2, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow-artifacts/artifacts/e33da3fbd6fd4dbca196d26da02ae894/d779d3e651874f389885ca13a5ea937f/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-02-09 21:24:25,752: WARNING: connectionpool: Retrying (Retry(total=1, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow-artifacts/artifacts/e33da3fbd6fd4dbca196d26da02ae894/d779d3e651874f389885ca13a5ea937f/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-02-09 21:28:57,926: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 21:28:57,930: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 21:28:57,933: INFO: common: created directory at: artifacts]
[2024-02-09 21:29:11,025: INFO: common: json file saved at: scores.json]
[2024-02-09 21:29:15,545: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-09 21:29:16,252: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmptb9a8j0v\model\data\model\assets]
