[2024-01-26 23:01:19,887: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-26 23:01:19,906: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-26 23:01:19,910: INFO: common: created directory at: artifacts]
[2024-01-26 23:01:19,913: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-26 23:02:16,797: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-26 23:02:16,805: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-26 23:02:16,807: INFO: common: created directory at: artifacts]
[2024-01-26 23:02:16,810: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-26 23:03:48,271: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-26 23:03:48,278: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-26 23:03:48,281: INFO: common: created directory at: artifacts]
[2024-01-26 23:03:48,283: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-09 20:53:58,785: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 20:53:58,789: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 20:53:58,790: INFO: common: created directory at: artifacts]
[2024-02-09 20:54:11,489: INFO: common: json file saved at: scores.json]
[2024-02-09 20:56:58,657: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 20:56:58,667: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 20:56:58,669: INFO: common: created directory at: artifacts]
[2024-02-09 20:57:11,413: INFO: common: json file saved at: scores.json]
[2024-02-09 20:57:14,722: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-09 20:57:15,602: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmpx_ryn210\model\data\model\assets]
[2024-02-09 20:59:53,965: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow-artifacts/artifacts/e33da3fbd6fd4dbca196d26da02ae894/72f3be0af8f045be81d5d68c7af84991/artifacts/model/data/model/variables/variables.data-00000-of-00001]
